config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/' => 'homes#top'
  get 'about' => 'homes#about'

  resources :decks do
    resources :cards
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck

  validates :front, presence: true
  validates :back, presence: true
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :relationships
  has_many :users, through: :relationships
  has_many :cards, dependent: :destroy

  validates :name, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :deck
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :relationships
  has_many :decks, through: :relationships

  def relationship(deck_id)
    relationships.create(deck_id: deck_id)
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    about_path
  end
  
  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_deck, only: [:index, :new, :create]
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  def index
    @cards = @deck.cards
  end

  def show
  end

  def new
    @card = @deck.cards.build
  end

  def create
    @card = @deck.cards.build(card_params)
    if @card.save
      redirect_to deck_card_path(@deck, @card), notice: 'カードが作成されました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @card.update(card_params)
      redirect_to deck_card_path(@deck, @card), notice: 'カードが更新されました'
    else
      render :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to deck_cards_path(@deck), notice: 'カードが削除されました'
  end

  private

  def set_deck
    @deck = Deck.find(params[:deck_id])
  end

  def set_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:front, :back)
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]

  def index
    @decks = current_user.decks
  end

  def show
    @deck = Deck.find(params[:id])
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = Deck.new(deck_params)
    if @deck.save
      current_user.relationship(@deck.id)
      redirect_to deck_path(@deck), notice: 'デッキが作成されました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @deck.update(deck_params)
      redirect_to deck_path(@deck), notice: 'デッキが更新されました'
    else
      render :edit
    end
  end

  def destroy
    @deck.destroy
    redirect_to decks_path, notice: 'デッキが削除されました'
  end

  private

  def set_deck
    @deck = Deck.find(params[:id])
  end

  def deck_params
    params.require(:deck).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/cards/_editform.html.erb
<%= form_with(model: [@deck, @card], local: true) do |form| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% @card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :front, '表:' %>
    <%= form.text_field :front %>
  </div>

  <div class="field">
    <%= form.label :back, '裏:' %>
    <%= form.text_field :back %>
  </div>

  <div class="actions">
    <%= form.submit '更新' %>
  </div>
<% end %>

app/views/cards/_form.html.erb
<%= form_with(model: [@deck, @card], local: true) do |form| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% @card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :front, '表:' %>
    <%= form.text_field :front %>
  </div>

  <div class="field">
    <%= form.label :back, '裏:' %>
    <%= form.text_field :back %>
  </div>

  <div class="actions">
    <%= form.submit '保存' %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>カード編集</h1>

<%= render 'editform' %>

<%= link_to '詳細に戻る', deck_card_path(@deck, @card) %> |
<%= link_to '一覧に戻る', deck_cards_path(@deck) %>

app/views/cards/index.html.erb
<h1>カード一覧</h1>

<table>
  <thead>
    <tr>
      <th>表</th>
      <th>裏</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.front %></td>
        <td><%= card.back %></td>
        <td>
          <%= link_to '詳細', card %>
          <%= link_to '編集', edit_deck_card_path(@deck, card) %>
          <%= link_to '削除', deck_card_path(@deck, card), method: :delete, data: { confirm: '本当に削除しますか?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '新しいカードを作成', new_deck_card_path(@deck) %>

app/views/cards/new.html.erb
<h1>新しいカードを作成</h1>

<%= render 'form' %>

<%= link_to '一覧に戻る', deck_cards_path(@deck) %>

app/views/cards/show.html.erb
<h1>カード詳細</h1>

<p><strong>表:</strong> <%= @card.front %></p>
<p><strong>裏:</strong> <%= @card.back %></p>

<%= link_to '編集', edit_deck_card_path(@deck, @card) %> |
<%= link_to '一覧に戻る', deck_cards_path(@deck) %>

app/views/decks/_editform.html.erb
<%= form_with(model: @deck, local: true) do |form| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
        <% @deck.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'デッキ名:' %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit '更新' %>
  </div>
<% end %>

app/views/decks/_form.html.erb
<%= form_with(model: @deck, local: true) do |form| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
        <% @deck.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'デッキ名:' %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit '保存' %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>デッキ編集</h1>

<%= render 'editform' %>

<%= link_to '詳細に戻る', deck_path(@deck) %> |
<%= link_to '一覧に戻る', decks_path %>

app/views/decks/index.html.erb
<h1>デッキ一覧</h1>

<ul>
  <% @decks.each do |deck| %>
    <li>
      <%= link_to deck.name, deck %>
      (カード数: <%= deck.cards.count %>)
    </li>
  <% end %>
</ul>

<%= link_to '新しいデッキを作成', new_deck_path %>

app/views/decks/new.html.erb
<h1>新しいデッキを作成</h1>

<%= render 'form' %>

<%= link_to '一覧に戻る', decks_path %>

app/views/decks/show.html.erb
<h1>デッキ詳細</h1>

<h2><%= @deck.name %></h2>

<h3>カード一覧</h3>
<ul>
  <% @deck.cards.each do |card| %>
    <li><%= card.front %> - <%= card.back %></li>
  <% end %>
</ul>

<%= link_to '新しいカードを作成', new_deck_card_path(@deck) %>
<%= link_to '編集', edit_deck_path(@deck) %> |
<%= link_to '一覧に戻る', decks_path %>

app/views/homes/about.html.erb
<h1>about</h1>

app/views/homes/top.html.erb
<h1>test</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vocabula</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <li>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "新規登録", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "ログイン", new_user_session_path %>
        </li>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>